{"name": "test_02", "status": "failed", "statusDetails": {"message": "AssertionError: 等价公式错误", "trace": "self = <jst_rebuild.demo.test_file.TestMathFunc object at 0x0000000003AD8DD8>\n\n    def test_02(self):\n        if not  5==4:\n>          raise AssertionError(\"等价公式错误\")\nE          AssertionError: 等价公式错误\n\njst_rebuild\\demo\\test_file.py:10: AssertionError"}, "start": 1592293362854, "stop": 1592293362855, "uuid": "dd78b574-2cc9-4c71-92b1-b89b4e42ba46", "historyId": "5ec1cf56bbe2882f5b2f9df51b1eda19", "testCaseId": "3ab17fc056c393a4bd7bf793c9f7dfaf", "fullName": "jst_rebuild.demo.test_file.TestMathFunc#test_02", "labels": [{"name": "parentSuite", "value": "jst_rebuild.demo"}, {"name": "suite", "value": "test_file"}, {"name": "subSuite", "value": "TestMathFunc"}, {"name": "host", "value": "WangLiu"}, {"name": "thread", "value": "10540-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "jst_rebuild.demo.test_file"}]}